/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-placar-gincana-Ly6r4eihBpbzS1I-Quc0jvLE1-iNyhql",
  "version": "2020-11-20"
}

export default ebconfig;